### PR TITLE
OPENDCS-13 add in a time interval threshold to only process contiguou…

### PR DESCRIPTION
**Pull request by adamkorynta**
…s data so that gaps don't end up getting filled in by downstream processes

### CODE REVIEW

**Comment by adamkorynta** [comment]
This change still needs testing

**Comment by MikeNeilson** [comment]
... that is, way simpler that I was originally thinking it would be to do that. However it would need to be separately put in https://github.com/opendcs/opendcs/blob/c5cd9f7933c23ea1d3450f510e9f148d54140990/src/main/java/decodes/cwms/CwmsTimeSeriesDb.java#L1287.

However hold off. once the connection pool branch gets merge in the getNewData functions will get moved around.

**Review by MikeNeilson — CHANGES_REQUESTED** [review]
There will need to be changes after a different branch is moved it so just keeping this one from accidentally get merged in.

**Review by mikecovesw — COMMENTED** [review]
The approach is good. Stop when a large gap is seen. This will force CCP to only work on relatively contiguous data.
Two things:
1. The getNewData method has been moved to the TimeSeriesDAO (and subclasses for HDB, OpenTSDB, and CWMS). It is no longer in the tsdb class directly. (see email I just sent explaining this.)
2. This commit is for the OpenTSDB subclass, not CWMS. I think you want to make your mods in decodes.cwms.CwmsTimeSeriesDAO.

**Comment by adamkorynta** [comment]
Moved code change to PR: https://github.com/opendcs/opendcs/pull/86

**Pull request closed without merging**
