### PR TITLE
remove stale information.

### PR DESCRIPTION
**Pull request by MikeNeilson**
Forgot to remove the branch status info from the README.

### CODE REVIEW

**Comment by MikeNeilson** [comment]
I've expanded the CONTRIBUTING.md file with more expectations. Given the Mike M is eventually going to not write as much code and there are a few more vendors starting to maybe hop in. It seemed prudent to make sure solid expectations are in order in case of any conflicts and such.

**Comment by agilmore2** [comment]
I like it. I'll make a few edits. ;)

**Comment by MikeNeilson** [comment]
Did you want to make those edits before or after we merge the current form in? Or just put inline comments in to what you think it should be?

**Comment by agilmore2** [comment]
PR made to that branch.

**Comment by MikeNeilson** [comment]
Will give this until Friday for comment, then merge.

**Pull request merged**
