### PR TITLE
Metarparser

### LINKED ISSUE #339: Ability for OpenDCS to read METAR files and parse into readable formats
**Is your feature request related to a problem? Please describe.**
The abstract web pull feature in OpenDCS allows you to read human-readable data and parse it into CWMS time series, but to my knowledge is not able to parse something as complex as a METAR message.  I am also not sure whether OpenDCS allows you to pull data from an LDM.

**Describe the solution you'd like**
Request the ability to read METAR messages and decode them.

**Describe alternatives you've considered**
This data ingest process is currently done with a METAR decoder java program written by @hoffmanjs, which reads the METAR files from the LDM, runs them through a basic screening process, then parses them into human-readable shef files and pushes them through processShefit to pull the data into the Oracle database.  Our understanding from what we've been told about the cloud migration is that these jobs cannot be there in CWBI, and we need to look at alternative ways to get the data.

**Additional context**
METAR (meteorological data stations from NOAA) data may also be able to be pulled through an abstract web source if ingesting LDM data isn't possible in OpenDCS.  More research would need to be done on this.  A sample METAR message and it's decoded data follows.  @hoffmanjs can also provide NOAA's documentation on how to decode METAR messages, which is quite extensive due to the types of data that could be in a message.  We require 10 parameters from these messages to run our reservoir evaporation program.

**Sample Message**
KBIS 181252Z 32018G26KT 10SM -RA BKN016 BKN021 OVC080 10/08 A2972 RMK AO2 PK WND 29027/1203 RAE05B43 SLP065 P0001 T01000083

**Decoded data**
METAR for KBIS (Bismarck Arpt, ND, US) observed at 1252 UTC 18 Oct 2023
  Text: KBIS 181252Z 32018G26KT 10SM -RA BKN016 BKN021 OVC080 10/08 A2972 RMK AO2 PK WND 29027/1203 RAE05B43 SLP065 P0001 T01000083
  Temperature: 10C (50.0 F)
  Dewpoint: 8.3C (46.9 F)
  Altimeter: 29.72 inches Hg (1006.5 mb)
  Sea level pressure: 1006.5 mb
  Winds: from 320 degrees at 18 knots gusting to 26 knots
  Visibility: 10+ sm
  Ceiling: 1600 feet AGL
  Clouds: broken clouds at 1600 feet AGL, broken clouds at 2100 feet AGL, overcast cloud deck at 8000 feet AGL
  Weather: -RA (light rain)

### PR DESCRIPTION
**Pull request by hoffmanjs**
## Problem Description
Adding the JWeather metar parser code

Fixes #339

Describe the problem you are trying to solve.

## Solution

Describe your solution.

## how you tested the change

Describe what was done to test the change. This section can be left blank 
if automated tests demonstrating usage are provided in the PR.

## Where the following done:

- [ ] Tests. Check all that apply:
   - [ ] Unit tests created or modified that run during ant test.
   - [ ] Integration tests created or modified that run during integration testing
         (Formerly called regression tests.)
   - [ ] Test procedure descriptions for manual testing
- [ ] Was relevant documentation updated?
- [ ] Were relevant config element (e.g. XML data) updated as appropriate

If you aren't sure leave unchecked and we will help guide you to want needs changing where.

### CODE REVIEW

**Comment by agilmore2** [comment]
LGPL code, can we include it like this, or do we need it as a separate library?

**Comment by MikeNeilson** [comment]
Has to be pulled in as a separate library. At least I'm pretty sure and it's certainly the safest bet.

@hoffmanjs I just created #667, You can use that to create an independent jar file that include the appropriate function that any opendcs user can choose to pull in.

Due to the licensing restrictions I'm closing this PR, it shouldn't go into the main OpenDCS code base. Nothing wrong with the code itself, and the overall design is fine, just OpenDCS following the rules as best as possible.

@agilmore2 good catch.

**Comment by ktarbet** [comment]
@hoffmanjs ,  Sorry I lead you the wrong direction!  

@MikeNeilson  should this independent jar have it's own repository within opendcs?

**Comment by MikeNeilson** [comment]
Probably better to put it over at https://github.com/usace-watermanagement 
Not that it needs to be a hard stance of only Apache compatible code in OpenDCS seems most appropriate for something developed on a slightly separate cycle.

**Pull request closed without merging**
