### PR TITLE
Devops/switch to tightvnc for auto gui

### LINKED ISSUE #419: Flakey GUI test in ubuntu github action
**Describe the bug**
The ProfileManagerFrame test when running in the action appears to be slightly flaky.
Reviewing the generated session capture the mouse appears to get stuck and unable to 
click a JOptionPane button to proceed.

**To Reproduce**
1. Run build.yml workflow
2. wait for test
3. if failed go to action summary and download ubuntu artifact, stepping frame by frame (e in VLC) you can see the mouse in the wrong location.
4. run test again (in the actions -> re-run failed workflows)
5. may or may not see success.

**Expected behavior**
Consistent behavior from the GUI environment.

**Screenshots**

**Desktop/ServerSide (please complete the following information):**
 - OS: ubuntu-latest (22.04)
 - Version: master branch

**Additional context**
If we can find no other rhime or reason we may just try this: https://github.com/gluonhq/substrate/pull/433/files

### PR DESCRIPTION
**Pull request by MikeNeilson**
## Problem Description

Fixes #419 . ... maybe.

Describe the problem you are trying to solve.

## Solution

Instead of Xfvb, use tightvnc. May still need to add a window manager.

## how you tested the change

Test failure is only happening during github action automation. Will test by re-running the action a few times.

## Where the following done:

- [ ] Tests. Check all that apply:
   - [ ] Unit tests created or modified that run during ant test.
   - [ ] Integration tests created or modified that run during integration testing
         (Formerly called regression tests.)
   - [ ] Test procedure descriptions for manual testing
- [ ] Was relevant documentation updated?
- [ ] Were relevant config element (e.g. XML data) updated as appropriate

If you aren't sure leave unchecked and we will help guide you to want needs changing where.

### CODE REVIEW

**Comment by agilmore2** [comment]
Are all those commits related to this change? The first commit appears to be about XML->SQL?

**Comment by MikeNeilson** [comment]
Oops, forgot to rebase, all those changes just got merged in.

**Comment by MikeNeilson** [comment]
@agilmore2 now it should look like more of a sane change.

**Comment by MikeNeilson** [comment]
Going to bring this back down local; test seems to be working fine but ffmpeg isn't recording the video any more, just black.

**Pull request closed without merging**
